general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  #"~/.config/alacritty/catppuccin-mocha.toml"
]

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
#background = '#282828'
background = '#1d2021'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[cursor.style]
shape = "Beam"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]
